name: Testing workflow variables

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Jason, it's Sunday"
        run: echo "$Greeting $First_Name is using $cloud!"
        env:
          First_Name: Jason
